// @flow

// flow-typed signature: bd4f0da653ddbea71eae89866d8a2cac
// flow-typed version: <<STUB>>/react-content-loader_v4.3.4/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-content-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-content-loader' {
  declare type Props = $ReadOnly<{|
    animate?: boolean,
    backgroundColor?: string,
    backgroundOpacity?: number,
    baseUrl?: string,
    foregroundColor?: string,
    foregroundOpacity?: number,
    gradientRatio?: number,
    interval?: number,
    rtl?: boolean,
    speed?: number,
    title?: string,
    uniqueKey?: string,
    width?: string | number,
    height?: string | number,
  |}>;

  declare type ContentLoaderProps = $ReadOnly<{|
    ...Props,
    children: React$Node,
    viewBox: string,
  |}>;

  declare export default function ContentLoader(props: ContentLoaderProps): React$Node;
  declare export function Facebook(props: Props): React$Node;
  declare export function Instagram(props: Props): React$Node;
  declare export function Code(props: Props): React$Node;
  declare export function List(props: Props): React$Node;
  declare export function BulletList(props: Props): React$Node;
}
